from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.home, name='home'),
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('login_user/', views.login_user, name='login_user'),
    path('dashboard/', views.user_dashboard, name='user_dashboard'),
    path('apply/<int:job_id>/', views.apply_job, name='apply_job'),
    path('my-applications/', views.my_applications, name='my_applications'),
    path('logout/', views.logout_user, name='logout'),
    path('employer_login/', views.employer_login, name='employer_login'),
    path('admin_login/', views.admin_login, name='admin_login'),
    path('adminlogin/', views.adminlogin, name='adminlogin'),
    path('admin_dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('employerlogin/', views.employerlogin, name='employerlogin'),
    path('employer_dashboard/', views.employer_dashboard, name='employer_dashboard'),
    path('logout_employer/', views.logout_employer, name='logout_employer'),
    path('logout_admin/', views.logout_admin, name='logout_admin'),
    path('post-job/', views.post_job, name='post_job'),
    path('job-listings/', views.job_list_view, name='job_list_view'),
    path('job/view/<int:job_id>/', views.job_view, name='job_view'),
    path('job/edit/<int:job_id>/', views.job_edit, name='job_edit'),
    path('job/delete/<int:job_id>/', views.job_delete, name='job_delete'),
    path('dashboard/users/', views.user_list, name='user_list'),
    path('dashboard/users/edit/<int:user_id>/', views.user_edit, name='user_edit'),
    path('dashboard/users/delete/<int:user_id>/', views.user_delete, name='user_delete'),
    path('dashboard/employers/', views.employer_list, name='employer_list'),
    path('dashboard/employers/edit/<int:employer_id>/', views.employer_edit, name='employer_edit'),
    path('dashboard/employers/delete/<int:employer_id>/', views.employer_delete, name='employer_delete'),
    path('dashboard/employers/add/', views.employer_add, name='employer_add'),
    path('employer/applications/', views.view_applications, name='view_applications'),
    path('application/<int:app_id>/detail/', views.view_application_detail, name='view_application_detail'),
    path('application/<int:app_id>/status/', views.update_application_status, name='update_application_status'),
    path('dashboard/jobs/', views.admin_job_list, name='admin_job_list'),
    path('dashboard/jobs/view/<int:job_id>/', views.admin_job_view, name='admin_job_view'),
    path('dashboard/jobs/edit/<int:job_id>/', views.admin_job_edit, name='admin_job_edit'),
    path('dashboard/jobs/delete/<int:job_id>/', views.admin_job_delete, name='admin_job_delete'),
    path('admindashboard/applications/', views.admin_applications, name='admin_applications'),
    path('admindashboard/applications/<int:app_id>/view/', views.admin_application_view, name='admin_application_view'),
    path('admindashboard/applications/<int:app_id>/edit/', views.admin_application_edit, name='admin_application_edit'),
    path('admindashboard/applications/<int:app_id>/delete/', views.admin_application_delete, name='admin_application_delete'),
    path('external-jobs/', views.external_jobs, name='external_jobs'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)