# Generated by Django 5.0.8 on 2025-06-26 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_employer'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
