# Generated by Django 5.0.8 on 2025-06-26 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_jobpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='employer',
        ),
    ]
