# Generated by Django 5.0.8 on 2025-06-27 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_remove_jobpost_employer'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='employer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='job.employer'),
            preserve_default=False,
        ),
    ]
