# Generated by Django 5.0.8 on 2025-06-27 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_jobpost_employer'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='company_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
