# Generated by Django 5.0.8 on 2025-06-28 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='agree_terms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='education',
            field=models.TextField(default='Not Provided'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='experience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='strength',
            field=models.TextField(default='Not Provided'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='why_interested',
            field=models.TextField(default='Not Provided'),
        ),
    ]
